version: "3"
services:
  master: 
    image: mysql:${TAG}
    restart: unless-stopped
    env_file:
      - env/base.env
      - env/master.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MASTER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=rd_backend_code
      - MYSQL_PASSWORD=1qaz!QAZ
      - MYSQL_DATABASE=sport_local_hao
    ports:
      - "4006:3306"
    expose:
      - "3306"
    networks:
       backend:
          ipv4_address: 172.31.0.11
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/mysqld.cnf
      - mysql-master-data:/var/lib/mysql
      - ./init-db/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    command: [
      "--server-id=${MASTER_SERVER_ID}"
    ]
  node1:
    image: mysql:${TAG}
    restart: unless-stopped
    env_file:
      - env/base.env
      - env/node.env
    environment:
      - MYSQL_ROOT_PASSWORD=${NODE_MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
       backend:
          ipv4_address: 172.31.0.21
    depends_on:
      - master
    volumes:
      - ./node.cnf:/etc/mysql/conf.d/mysqld.cnf
      - mysql-node1-data:/var/lib/mysql
      - ./init-db/init-node.sh:/docker-entrypoint-initdb.d/init-node.sh
    command: [
      "--server-id=${NODE_1_SERVER_ID}"
    ]
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
volumes:
  mysql-master-data:
  mysql-node1-data: