#!/bin/bash

set -e
mysql -u root -p${MYSQL_ROOT_PASSWORD} -h localhost \
-e "CREATE USER '${MYSQL_REPLICATION_USER}'@'${MYSQL_HOST}' IDENTIFIED BY '${MYSQL_REPLICATION_USER_PWD}'; \
GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'${MYSQL_HOST}';"
